name: Use reusable example
on:
  pull_request_target:
    branches: [ main ]
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
jobs:
  run-reusable-example:
    uses: "./.github/workflows/reusable_example.yaml"
    if: ${{ !github.event.pull_request.draft }}
    secrets:
      message: ${{ secrets.MESSAGE }}
